### ISSUE TITLE
Cannot find app module

### ISSUE THREAD

**Issue by mgeiser81** [koroandr/generator-express-typescript#6]
After generating the project and doing **npm start** I get the following error. 

Error: Cannot find module '../app'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Source\Express-Ts\bin\www:7:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I have done tried removing the node_modules folder, clearing npm cache, and doing npm install a couple times and I always get this error. 

Anyone else run into this?

**Comment by yoyoys** [comment]
just run `gulp`, that's all. 😄   
p.s. the port number is 3000
